name: sqlite3_bridge
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.13.1

dependencies:
  ffi: ^2.2.0
  libhook:
    git: https://github.com/qqmagic5/libhook.git
  libffigen:
    git: https://github.com/qqmagic5/libffigen.git

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
